/* -*- Mode: C++; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsIInputStream.idl"

[scriptable, builtinclass, uuid(d533a9a6-cbb2-4e03-96b0-fa86a44decd2)]
interface nsIInputStreamWrapper : nsISupports
{
    nsIInputStream getWrappedStream();
};
